# Setup
title:               barnld's blog
tagline:             'A blog for my coding projects and tinkering'
description:         'No description yet, sorry.'
url:                 https://barnld.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Barnabas Illes
  url:               
  email:             barnld97@zohomail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
